---
name: custom-os
description: This is my personal OS image.
base-image: ghcr.io/wayblueorg/hyprland-nvidia-open
image-version: 42
modules:
  - type: files
    files:
      - source: system
        destination: /
  - type: dnf
    repos:
      copr:
        - lizardbyte/stable
        - felfert/cherryrgb
  - type: rpm-ostree
    install:
      - Sunshine
      - nautilus
      - cherryrgb
      - restic
      - rclone

  - from-file: common/dx.yml

  - type: default-flatpaks
    notify: true
    system:
      repo-url: https://dl.flathub.org/repo/flathub.flatpakrepo
      repo-name: flathub
      repo-title: "Flathub (system-wide)"
      install:
        - org.freecad.FreeCAD
        - com.spotify.Client
        - com.discordapp.Discord
        - io.github.flattool.Warehouse
        - com.teamspeak.TeamSpeak3
        - com.valvesoftware.Steam
        - org.filezillaproject.Filezilla
        - org.blender.Blender
        - org.blender.Blender.Codecs
        - com.github.iwalton3.jellyfin-media-player
        - com.github.Matoking.protontricks
        - im.riot.Riot
        - org.godotengine.Godot3
        - org.signal.Signal
        - org.zulip.Zulip
        - org.gimp.GIMP
        - org.gimp.GIMP.HEIC
        - org.mozilla.firefox
        - org.pulseaudio.pavucontrol
        - com.dec05eba.gpu_screen_recorder
        - org.libreoffice.LibreOffice
        - net.lutris.Lutris
        - io.missioncenter.MissionCenter
        - com.bitwarden.desktop
        - com.rtosta.zapzap
    user:
      repo-name: flathub
  - type: script
    snippets:
      - "setcap 'cap_sys_admin+p' /usr/bin/sunshine-v*"
  - type: signing

